name: Deploy with AWS Copilot

on:
  workflow_dispatch:  # Trigger on pushes to the main branch; adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: setup-copilot
    steps:
      - name: Download Copilot CLI from Artifacts
        uses: actions/download-artifact@v4
        with:
          name: copilot-cli
          path: /usr/local/bin

      - name: Ensure Copilot is executable
        run: chmod +x /usr/local/bin/copilot

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Action_Role
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: git pull origin ${{ github.head_ref }} 

      # Step 4: Run Copilot commands
      - name: Initialize and deploy using AWS Copilot
        env:
          AWS_REGION: us-east-1  # Set your AWS region
        run: |
          # Initialize a new environment (only needed if not done already)
          copilot env init --name test-env --region {{ secrets.AWS_REGION }}
          
          # Initialize a new application (only needed if not done already)
          copilot init --app my-app --svc yesy-svc --type "Load Balanced Web Service" --deploy

          # Deploy the application (run this on every change)
          copilot svc deploy --name test-svc --env test-env

          # Optional: Check service status
          copilot svc status --name test-svce --env test-env

      - name: Commit AWS Copilot Staging Config
        if: env.environment_exists == 'false'
        run: |
          git config --global user.email "pradeep.reddy@ryvalx.com"
          git config --global user.name "PradeepReddy019"
          git add -A  # Adds all changes, including untracked files
          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
          git push origin HEAD:${{ github.ref }}  # Ensure you're pushing to the correct branch
        shell: bash
